### PR TITLE
[bug-fix] repository.createProcessDefinitionQuery().processDefinitionIds(new HashSet()).list() get Error.

### LINKED ISSUE #3622: [bug] repository.createProcessDefinitionQuery().processDefinitionIds(new HashSet()).list() get Error.
fix in:
https://github.com/Activiti/Activiti/pull/3567

### PR DESCRIPTION
**Pull request by XenoAmess**
Fixes https://github.com/Activiti/Activiti/issues/3622

### CODE REVIEW

**Comment by mteodori** [comment]
Thanks, can you please add a unit test for the issue?

**Comment by XenoAmess** [comment]
> Thanks, can you please add a unit test for the issue?

@mteodori 
with pleasure.
unit test added.

**Comment by XenoAmess** [comment]
@mteodori Hi. rebased. all checks passed. please consider re-review.

File: activiti-core/activiti-engine/src/test/java/org/activiti/engine/test/api/repository/ProcessDefinitionQueryTest.java [hunk 1]
```diff
@@ -338,4 +338,8 @@ public void testQueryWithNullArgs() {
       .isThrownBy(() -> repositoryService.createProcessDefinitionQuery().processDefinitionKeys(null));
   }
 
+  public void testQueryWithEmptyIdSet() {
+    repositoryService.createProcessDefinitionQuery().processDefinitionIds(new HashSet<>(0)).list();
```
Comment (erdemedeiros) [inline activiti-core/activiti-engine/src/test/java/org/activiti/engine/test/api/repository/ProcessDefinitionQueryTest.java]: Could you add an assertion to your test, please?
It could be simply `assertThat(...).isNotEmpty()`.

**Review by erdemedeiros — CHANGES_REQUESTED** [review]
Hi @XenoAmess, thank you for adding the test. Would you mind adding an assertion to it?
Also, could you please, create an issue describing the issue and reference it to your PR?

File: activiti-core/activiti-engine/src/test/java/org/activiti/engine/test/api/repository/ProcessDefinitionQueryTest.java (hunk 1 above)
Comment (XenoAmess) [reply activiti-core/activiti-engine/src/test/java/org/activiti/engine/test/api/repository/ProcessDefinitionQueryTest.java]: > Could you add an assertion to your test, please?
> It could be simply `assertThat(...).isNotEmpty()`.

@erdemedeiros
OK. will do it now.

**Review by erdemedeiros — APPROVED** [review]
Thanks! Please, don't forget to create a [Github issue](https://github.com/Activiti/Activiti/issues/new) and reference it in this PR.

File: activiti-core/activiti-engine/src/test/java/org/activiti/engine/test/api/repository/ProcessDefinitionQueryTest.java (hunk 1 above)
Comment (XenoAmess) [reply activiti-core/activiti-engine/src/test/java/org/activiti/engine/test/api/repository/ProcessDefinitionQueryTest.java]: @erdemedeiros done. running ci.

**Comment by XenoAmess** [comment]
> Thanks! Please, don't forget to create a [Github issue](https://github.com/Activiti/Activiti/issues/new) and reference it in this PR.

@erdemedeiros done in https://github.com/Activiti/Activiti/issues/3622
