### PR TITLE
Activiti/Activiti#3620 Add diagram rendering for errored activities

### LINKED ISSUE #3620: Error color state diagram is not displayed
The Red color of the failed tasks is not rendered in the same way as the completed or current tasks.
It needs to be displayed as a Red highlighting of the errored tasks.

### PR DESCRIPTION
**Pull request by miguelruizdev**
Fixes Activiti/Activiti#3620

### CODE REVIEW

**Review by zoltanpalfi — APPROVED** [review]

File: activiti-core/activiti-image-generator/src/main/java/org/activiti/image/impl/DefaultProcessDiagramCanvas.java [hunk 1]
```diff
@@ -1417,6 +1420,18 @@ public void drawGatewayHighLightCompleted(GraphicInfo graphicInfo) {
         g.setStroke(originalStroke);
     }
 
+    public void drawGatewayHighLightErrored(GraphicInfo graphicInfo) {
```
Comment (erdemedeiros) [inline activiti-core/activiti-image-generator/src/main/java/org/activiti/image/impl/DefaultProcessDiagramCanvas.java]: You can reuse some code here by extracting another method that takes the color as a parameter. In this way, both  `drawGatewayHighLightCompleted ` and `drawGatewayHighLightErrored` will call this new method but passing a different color.

File: activiti-core/activiti-image-generator/src/main/java/org/activiti/image/impl/DefaultProcessDiagramCanvas.java [hunk 2]
```diff
@@ -1649,6 +1670,27 @@ public void drawEventHighLightCompleted(int x,
         g.setStroke(originalStroke);
     }
 
+    public void drawEventHighLightErrored(int x,
```
Comment (erdemedeiros) [inline activiti-core/activiti-image-generator/src/main/java/org/activiti/image/impl/DefaultProcessDiagramCanvas.java]: Same here: you can extract a method that will be reused by both `drawEventHighLightCompleted` and `drawEventHighLightErrored`.

File: activiti-core/activiti-image-generator/src/main/java/org/activiti/image/impl/DefaultProcessDiagramGenerator.java [hunk 3]
```diff
@@ -1131,6 +1153,27 @@ private static void drawGatewayHighLightCompleted(DefaultProcessDiagramCanvas pr
         processDiagramCanvas.drawGatewayHighLightCompleted(graphicInfo);
     }
 
+    private static void drawTaskHighLightErrored(DefaultProcessDiagramCanvas processDiagramCanvas,
+        GraphicInfo graphicInfo) {
+        processDiagramCanvas.drawHighLightErrored((int) graphicInfo.getX(),
+            (int) graphicInfo.getY(),
+            (int) graphicInfo.getWidth(),
+            (int) graphicInfo.getHeight());
```
Comment (erdemedeiros) [inline activiti-core/activiti-image-generator/src/main/java/org/activiti/image/impl/DefaultProcessDiagramGenerator.java]: I'd prefer to have the entire `GraphicInfo` passed as a parameter, instead of splitting it into several parameters.

File: activiti-core/activiti-image-generator/src/main/java/org/activiti/image/impl/DefaultProcessDiagramGenerator.java [hunk 4]
```diff
@@ -1131,6 +1153,27 @@ private static void drawGatewayHighLightCompleted(DefaultProcessDiagramCanvas pr
...
+    }
+
+    private static void drawEventHighLightErrored(DefaultProcessDiagramCanvas processDiagramCanvas,
+        GraphicInfo graphicInfo) {
+        processDiagramCanvas.drawEventHighLightErrored((int) graphicInfo.getX(),
```
Comment (erdemedeiros) [inline activiti-core/activiti-image-generator/src/main/java/org/activiti/image/impl/DefaultProcessDiagramGenerator.java]: Same here: let's pass the entire `GraphicInfo`.

**Review by erdemedeiros — CHANGES_REQUESTED** [review]
Nice improvement!
Here are some suggestions.

**Review by erdemedeiros — APPROVED** [review]
LGTM!
