### PR TITLE
fix(AAE-2825): New serializer for IntegrationRequests produces wrong results #3316

### LINKED ISSUE #3316: New serializer for IntegrationRequests produces wrong results
In some cases, the new [ProcessVariablesMapSerializer](https://github.com/Activiti/Activiti/blob/develop/activiti-core/activiti-api-impl/activiti-api-process-model-impl/src/main/java/org/activiti/api/runtime/model/impl/ProcessVariablesMapSerializer.java) produces inconsitent values that [ProcessVariablesMapDeserializer](https://github.com/Activiti/Activiti/blob/develop/activiti-core/activiti-api-impl/activiti-api-process-model-impl/src/main/java/org/activiti/api/runtime/model/impl/ProcessVariablesMapDeserializer.java) is not able to deserialize. For instance, before adding support to [LocalDateTime](https://github.com/Activiti/Activiti/pull/3315), it was producing the following json: 
```json
{
  "id": "3e718a62-ce9d-4f6b-b7e4-ad0ff114d41f",
  "inBoundVariables": {},
  "outBoundVariables": {
    "variable": {
      "type": "map",
      "value": "05/06/2020, 15:02"
    }
  }
}
```

Note that `type` is defined as `map`, but the `value` is not a map.

### PR DESCRIPTION
**Pull request by igdianov**
Fixes #3316

This PR applies object type for serializing/deserializing integration request process variables that do not have registered type. 

The deserializer will fall back to regular key/value map in order to maintain backward compatibility with previous versions of Activiti Cloud integration context serialization using standard object mapper.

### CODE REVIEW

File: activiti-core/activiti-api-impl/activiti-api-process-model-impl/src/main/java/org/activiti/api/runtime/model/impl/ObjectValueToStringConverter.java [hunk 1]
```diff
@@ -0,0 +1,51 @@
...
+        this.objectMapper = objectMapper;
+    }
+
+    @Override
+    public String convert(ObjectValue source) {
+
+        try {
+            Map<String, Object> value = objectMapper.convertValue(source, Map.class);
+
+            if (Map.class.isInstance(value.get("object"))) {
```
Comment (erdemedeiros) [inline activiti-core/activiti-api-impl/activiti-api-process-model-impl/src/main/java/org/activiti/api/runtime/model/impl/ObjectValueToStringConverter.java]: It's probably better to extract a constant for `"object"`.

File: activiti-core/activiti-api-impl/activiti-api-process-model-impl/src/main/java/org/activiti/api/runtime/model/impl/ObjectValueToStringConverter.java [hunk 2]
```diff
@@ -0,0 +1,51 @@
...
+                Map<String, Object> object = objectMapper.convertValue(source.getObject(), Map.class);
+
+                if (object.containsKey("@class")) {
```
Comment (erdemedeiros) [inline activiti-core/activiti-api-impl/activiti-api-process-model-impl/src/main/java/org/activiti/api/runtime/model/impl/ObjectValueToStringConverter.java]: Same for`@class`.

File: activiti-core/activiti-api-impl/activiti-api-process-model-impl/src/main/java/org/activiti/api/runtime/model/impl/ProcessVariablesMapDeserializer.java [hunk 3]
```diff
@@ -45,13 +46,31 @@ public ProcessVariablesMapDeserializer(ConversionService conversionService) {
...
+                        result = ObjectValue.class.cast(result)
+                                                  .getObject();
+                    }
+
+                    map.put(name, result);
+                }
+                else {
+                    Object value = null;
+                    try {
+                        value = new ObjectMapper().treeToValue(entryValue,
```
Comment (erdemedeiros) [inline activiti-core/activiti-api-impl/activiti-api-process-model-impl/src/main/java/org/activiti/api/runtime/model/impl/ProcessVariablesMapDeserializer.java]: Shaw, we try to inject the `ObjectMapper` instead of creating a new one?

File: activiti-core/activiti-api-impl/activiti-api-process-model-impl/src/main/java/org/activiti/api/runtime/model/impl/ProcessVariablesMapDeserializer.java [hunk 4]
```diff
@@ -45,13 +46,31 @@ public ProcessVariablesMapDeserializer(ConversionService conversionService) {
...
+                                                               Object.class);
+                    } catch (JsonProcessingException e) {
+                        e.printStackTrace();
```
Comment (erdemedeiros) [inline activiti-core/activiti-api-impl/activiti-api-process-model-impl/src/main/java/org/activiti/api/runtime/model/impl/ProcessVariablesMapDeserializer.java]: Please, use logger instead of `printStackTrace()`.

File: activiti-core/activiti-api-impl/activiti-api-process-model-impl/src/main/java/org/activiti/api/runtime/model/impl/ProcessVariablesMapSerializer.java [hunk 5]
```diff
@@ -61,17 +59,20 @@ public void serialize(ProcessVariablesMap<String, Object> processVariablesMap,
...
         throws JsonProcessingException {
         ProcessVariableValue variableValue = null;
+
         if (value != null) {
             Class<?> entryValueClass = value.getClass();
+            String entryType = resolveEntryType(entryValueClass, value);
 
-            if (!conversionService.canConvert(entryValueClass, String.class)) {
-                value = objectMapper.writeValueAsString(value);
+            if("object".equals(entryType)) {
```
Comment (erdemedeiros) [inline activiti-core/activiti-api-impl/activiti-api-process-model-impl/src/main/java/org/activiti/api/runtime/model/impl/ProcessVariablesMapSerializer.java]: Re-use constant.

**Review by erdemedeiros — CHANGES_REQUESTED** [review]
Some small details.

File: activiti-core/activiti-api-impl/activiti-api-process-model-impl/src/main/java/org/activiti/api/runtime/model/impl/ProcessVariablesMapDeserializer.java (hunk 3 above)
Comment (igdianov) [reply activiti-core/activiti-api-impl/activiti-api-process-model-impl/src/main/java/org/activiti/api/runtime/model/impl/ProcessVariablesMapDeserializer.java]: @erdemedeiros I am afraid to do it because it may bring side effects. We should only consider to inject global object mapper to support some test case, I think.

File: activiti-core/activiti-api-impl/activiti-api-process-model-impl/src/main/java/org/activiti/api/runtime/model/impl/ProcessVariablesMapDeserializer.java (hunk 4 above)
Comment (igdianov) [reply activiti-core/activiti-api-impl/activiti-api-process-model-impl/src/main/java/org/activiti/api/runtime/model/impl/ProcessVariablesMapDeserializer.java]: done.

File: activiti-core/activiti-api-impl/activiti-api-process-model-impl/src/main/java/org/activiti/api/runtime/model/impl/ProcessVariablesMapSerializer.java (hunk 5 above)
Comment (igdianov) [reply activiti-core/activiti-api-impl/activiti-api-process-model-impl/src/main/java/org/activiti/api/runtime/model/impl/ProcessVariablesMapSerializer.java]: Done

File: activiti-core/activiti-api-impl/activiti-api-process-model-impl/src/main/java/org/activiti/api/runtime/model/impl/ObjectValueToStringConverter.java (hunk 1 above)
Comment (igdianov) [reply activiti-core/activiti-api-impl/activiti-api-process-model-impl/src/main/java/org/activiti/api/runtime/model/impl/ObjectValueToStringConverter.java]: Done

File: activiti-core/activiti-api-impl/activiti-api-process-model-impl/src/main/java/org/activiti/api/runtime/model/impl/ObjectValueToStringConverter.java (hunk 2 above)
Comment (igdianov) [reply activiti-core/activiti-api-impl/activiti-api-process-model-impl/src/main/java/org/activiti/api/runtime/model/impl/ObjectValueToStringConverter.java]: Done

File: activiti-core/activiti-api-impl/activiti-api-process-model-impl/src/main/java/org/activiti/api/runtime/model/impl/ProcessVariablesMapDeserializer.java (hunk 3 above)
Comment (erdemedeiros) [reply activiti-core/activiti-api-impl/activiti-api-process-model-impl/src/main/java/org/activiti/api/runtime/model/impl/ProcessVariablesMapDeserializer.java]: Ok. Let's keep a new instance of ObjectMapper in this case.

**Review by erdemedeiros — APPROVED** [review]
